region: us-west-2

function_name: put-menu
handler: put-menu.handler
role: feedback
description: update menu

aws_access_key_id: AKIAIDNWS6UHSPMUZOXA
aws_secret_access_key: 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