region: us-west-2

function_name: get-order
handler: get-order.handler
role: feedback
description: get order

aws_access_key_id: AKIAIDNWS6UHSPMUZOXA
aws_secret_access_key: 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